services:
  # The Redis Instance
  - type: redis
    name: job-queue-redis
    region: oregon
    plan: free
    ipAllowList: []

  # The Producer API
  - type: web
    name: job-queue-api
    runtime: docker
    region: oregon
    plan: free
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: job-queue-redis
          property: connectionString
      - key: PORT
        value: 4000

  # The Dashboard
  - type: web
    name: job-queue-dashboard
    runtime: docker
    region: oregon
    plan: free
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: job-queue-redis
          property: connectionString
      - key: DASHBOARD_PORT
        value: 5000
    dockerCommand: npm run start:dashboard

  # The Background Workers
  - type: web
    name: job-queue-worker
    runtime: docker
    region: oregon
    plan: free
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: job-queue-redis
          property: connectionString
      - key: PORT
        value: 8080
    dockerCommand: npm run start:worker
